server:
  port: 8080


spring:
  application:
    name: provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?characterEncoding=utf-8
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mapper/mapper/*.xml
  type-aliases-package: com.lpl.spring.model

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
